# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b35663d798ce540a9f9269cb39b44ca34964b758235f2c1db88e7115c52efe640929beff82d55e8eb5c5a9702438bbc5712647026ea80372ba7fd81116fec2a

test:
  secret_key_base: c47a03ca3ecf5f0278dd7616200c7cc9fad85c956be12b5d8c19c27c464855ed6b7866c4088e02d74381d8b0eae7ddd6f85822c47eb6069ba4359d0f3693f0ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
