# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7adb8871cb579b3d83c3489ca11c0e351c6ced3033931c83feea3d32f44dfb76e48af2443393f405ce09cb54ea4335ac06c8d2b823c510c9fe59d72a8b0912b

test:
  secret_key_base: f57555840b9336b55cce13101a7db3a7376e74ea7eb6133320734fff112073db8d38631a4f4f38577f6247bd76b248458cf18a3427c1798b1fea15b5d2c5241b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
